name: "Deploy documentation to GitHub Pages"
on:
  release:
    types:
      - created
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
        uv-version: ["0.6.6"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install UV ${{matrix.uv-version}}"
        run: pipx install poetry==${{matrix.uv-version}}
      - name: "Setup Python ${{matrix.python-version}}"
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: 'uv'
      - name: "Install dependencies"
        run: make install
      - name: "Configure Git Credentials"
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: make mkdocs-deploy
