name: "Release and deploy package to PyPI"

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  deploy:
    name: "Build and deploy to PyPI"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        uv-version: ["0.6.6"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
      - name: "Setup UV ${{matrix.uv-version}}"
        run: pipx install uv==${{matrix.uv-version}}
      - name: "Build package"
        run: uv build
      - name: "Publish package"
        run: uv publish --username=__token__ --password=${{secrets.PYPI_TOKEN}}
